all: main printEnv infiniteLoop

main:
	gcc -c main.c
	gcc -o main main.o

printEnv:
	gcc -c printEnv.c
	gcc -o printEnv printEnv.o

infiniteLoop:
	gcc -c infiniteLoop.c
	gcc -o infiniteLoop infiniteLoop.o

clear:
	rm main main.o printEnv printEnv.o plikCopy
	rm infiniteLoop infiniteLoop.o
